version: '3.9'
services:
  fit-friends_mongo:
    image: mongo:4.4
    restart: always
    container_name: fit-friends_mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    volumes:
      - fit-friends_mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh ${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  fit-friends_fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "fit-friends.fakesmtp"
    hostname: "fit-friends.fakesmtp"
    ports:
      - "${MAIL_SMTP_PORT}:8025"
      - "1083:8080"

  fit_friends_backend:
      container_name: fit-friends.backend
      depends_on:
        - fit-friends_mongo
        - fit_friends_fakesmtp
      restart: always
      image: ${IMAGE}
      env_file:
        - .stage.env
      ports:
        - ${BACKEND_PORT}:${BACKEND_PORT}
      networks:
        - fit_friends

volumes:
  fit-friends_mongo:

networks:
  fit-friends:
    driver: bridge
