# Get user notifications
GET http://localhost:3000/notifications HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjdlYzk3YmM3MGMzYThlMWY0ZmYiLCJlbWFpbCI6InVzZXJAZm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0yLnBuZyIsImlzUmVhZHkiOnRydWUsImlhdCI6MTcxMjA4MjU3MCwiZXhwIjoxNzEyMDgzNDcwfQ.6psHSCjERN7ALjPtFMuHDoUz-Jq5go1JxUAfEq65s74

###

# Delete notification by id
DELETE http://localhost:3000/notifications/660c4aa2cd46234a94f9a063 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZiMjdlYzk3YmM3MGMzYThlMWY0ZmYiLCJlbWFpbCI6InVzZXJAZm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwibmFtZSI6Iktla3MiLCJhdmF0YXIiOiJwaG90by0yLnBuZyIsImlzUmVhZHkiOnRydWUsImlhdCI6MTcxMjA4MjU3MCwiZXhwIjoxNzEyMDgzNDcwfQ.6psHSCjERN7ALjPtFMuHDoUz-Jq5go1JxUAfEq65s74

###
