export const BACKEND_URL = 'http://localhost:3000';
export const REQUEST_TIMEOUT = 5000;
export const STATIC_URL = `${BACKEND_URL}/static`;

export const APIRoute = {
  CheckAuth: '/auth/login',
  Login: '/auth/login',
  Register: '/auth/register',
  QuestionaryUser: 'users/questionary-user',
  QuestionaryCoach: 'users/questionary-coach',
  Users: '/users',
  AuthUser: '/users/my-data',
  UpdateUser: '/users/update',
  ReadyUsers: '/users/ready-users',
  UploadCertificate: '/users/certificates/upload',
  DeleteCertificate: '/users/certificates/delete',
  UpdateCertificate: '/users/certificates/update',
  Workouts: '/workouts',
  UpdateWorkout: '/workouts/update',
  CoachWorkouts: '/workouts/my-workouts',
  SpecialWorkouts: '/workouts/special',
  PopularWorkouts: '/workouts/popular',
  WorkoutsForUser: '/workouts/for-user',
  WorkoutsFromCoach: '/workouts/from-coach',
  CoachOrders: '/orders',
  Balances: '/balance',
  DecreaseBalance: '/balance/decrease',
  Friends: '/friends',
  AddFriend: '/friends/add',
  RemoveFriend: '/friends/remove',
  CreateWorkoutRequest: '/workout-requests',
  UpdateWorkoutRequest: '/workout-requests',
  Comments: '/comments',
  Notifications: '/notifications',
  CheckSubscription: '/subscribe/check',
  SubscribeTo: '/subscribe/add',
  UnsubscribeFrom: '/subscribe/remove',
} as const;
