export enum MetroStation {
  Avtovo = 'Автово',
  Akademicheskaya = 'Академическая',
  Baltiyskaya = 'Балтийская',
  Vladimirskaya = 'Владимирская',
  Vyborgskaya = 'Выборгская',
  Devyatkino = 'Девяткино',
  Lesnaya = 'Лесная',
  Narvskaya = 'Нарвская',
  Petrogadskaya = 'Петроградская',
  Pionerskaya = 'Пионерская',
  Pushkinskaya = 'Пушкинская',
  Sportivnaya = 'Спортивная',
  Udelnaya = 'Удельная',
  Chernyshevskaya = 'Чернышевская',
  Zvyozdnaya = 'Звёздная',
}
