# Create a new user (default)
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "dateOfBirth": "2012-02-22",
  "name": "Keks",
  "password": "123456",
  "avatar": "photo-1.png",
  "sex": "мужской",
  "role": "пользователь",
  "description": "Описание пользователя, описание пользователя.",
  "location": "Петроградская",
  "level": "профессионал",
  "workoutTypes": ["йога", "бег"],
  "isReady": true,
  "caloriesToLose": 5000,
  "caloriesPerDay": 1000,
  "timeForWorkout": "10-30 мин"
}

###

# Create a new user (coach)
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@found.local",
  "dateOfBirth": "2012-02-22",
  "name": "Keks",
  "password": "123456",
  "avatar": "photo-2.png",
  "sex": "мужской",
  "role": "тренер",
  "description": "Описание тренера, описание тренера.",
  "location": "Петроградская",
  "level": "профессионал",
  "workoutTypes": ["йога", "бег"],
  "isReady": true,
  "certificate": "certificate-1.jpg",
  "achievements": "Я кот и этим все сказано"
}

###

# Login user
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZkOWJmODEzNjMyYzBiNzUwZTE1NjEiLCJlbWFpbCI6InVzZXJAZmZmb3V1bm5uZGRkZGRkLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsIm5hbWUiOiJLZWtzIiwiYXZhdGFyIjoicGhvdG8tMi5wbmciLCJpc1JlYWR5Ijp0cnVlLCJ0b2tlbklkIjoiN2JiOTI0NmQtMGFhYy00OWQ2LTg4YjctYzdiNGUxY2E4NzM2IiwiaWF0IjoxNzExMTIzNTQ0LCJleHAiOjE3MTE3MjgzNDR9.NMXpLWqcgSOdj2YoDg41k22wOO9ZeFNTPz4B_0FsqMs

###

###

# Logout user
DELETE http://localhost:3000/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWZkOWJmODEzNjMyYzBiNzUwZTE1NjEiLCJlbWFpbCI6InVzZXJAZmZmb3V1bm5uZGRkZGRkLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsIm5hbWUiOiJLZWtzIiwiYXZhdGFyIjoicGhvdG8tMi5wbmciLCJpc1JlYWR5Ijp0cnVlLCJ0b2tlbklkIjoiN2JiOTI0NmQtMGFhYy00OWQ2LTg4YjctYzdiNGUxY2E4NzM2IiwiaWF0IjoxNzExMTIzNTQ0LCJleHAiOjE3MTE3MjgzNDR9.NMXpLWqcgSOdj2YoDg41k22wOO9ZeFNTPz4B_0FsqMs

###
